- name: "创建共享存储目录"
  file: dest={{ nfs_data }} state=directory

- name: "安装 nfs"
  package:
    name:
      - nfs-utils
    state: present


- name: "拷贝配置文件"
  template: src="exports.j2" dest="/etc/exports"
  notify: restart nfs

- name: "启动 nfs"
  systemd:
    name: nfs
    state: started
    enabled: yes
