- name: 启动 iscsid
  systemd:
    name: iscsid
    state: restarted
    enabled: yes
    daemon_reload: yes

- name: 加载内核模块
  raw: "{{ item }}"
  with_items:
    - "modprobe br_netfilter"
    - "modprobe rbd"
    - "modprobe dm_snapshot"
    - "modprobe dm_mirror"
    - "modprobe dm_thin_pool"
    - "modprobe nvme-tcp"
    - "modprobe nvmet"
    - "echo -e 'nvme-tcp\nnvmet' > /etc/modules-load.d/mayastor.conf"

- name: Add ipvs modules
  copy:
    src: ipvs.modules
    dest: /etc/sysconfig/modules/
    mode: '0755'

- name: enable ipvs
  shell: "/bin/bash /etc/sysconfig/modules/ipvs.modules"

- name: 开启k8s集群所需要的内核参数
  sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    state: present
    sysctl_file: /etc/sysctl.conf  # 修改 sysctl 配置文件，使参数永久生效
  with_items:
    - { name: 'net.ipv4.ip_forward', value: '1' }
    - { name: 'net.ipv4.conf.default.rp_filter', value: '1' }
    - { name: 'net.ipv4.conf.default.accept_source_route', value: '0' }
    - { name: 'kernel.sysrq', value: '0' }
    - { name: 'kernel.core_uses_pid', value: '1' }
    - { name: 'net.ipv4.tcp_syncookies', value: '1' }
    - { name: 'kernel.msgmnb', value: '65535' }
    - { name: 'kernel.msgmax', value: '65535' }
    - { name: 'kernel.shmmax', value: '68719476736' }
    - { name: 'kernel.shmall', value: '4294967296' }
    - { name: 'net.ipv4.tcp_max_tw_buckets', value: '6000' }
    - { name: 'net.ipv4.tcp_sack', value: '1' }
    - { name: 'net.ipv4.tcp_window_scaling', value: '1' }
    - { name: 'net.ipv4.tcp_rmem', value: '4096 87380 4194304' }
    - { name: 'net.ipv4.tcp_wmem', value: '4096 16384 4194304' }
    - { name: 'net.core.wmem_default', value: '8388608' }
    - { name: 'net.core.rmem_default', value: '8388608' }
    - { name: 'net.core.rmem_max', value: '16777216' }
    - { name: 'net.core.wmem_max', value: '16777216' }
    - { name: 'net.core.netdev_max_backlog', value: '262144' }
    - { name: 'net.core.somaxconn', value: '65000' }
    - { name: 'net.ipv4.tcp_max_orphans', value: '3276800' }
    - { name: 'net.ipv4.tcp_max_syn_backlog', value: '262144' }
    - { name: 'net.ipv4.tcp_timestamps', value: '0' }
    - { name: 'net.ipv4.tcp_synack_retries', value: '1' }
    - { name: 'net.ipv4.tcp_syn_retries', value: '1' }
    - { name: 'net.ipv4.tcp_tw_reuse', value: '1' }
    - { name: 'net.ipv4.tcp_mem', value: '94500000 915000000 927000000' }
    - { name: 'net.ipv4.tcp_fin_timeout', value: '10' }
    - { name: 'net.ipv4.ip_local_port_range', value: '1024 65000' }
    - { name: 'net.ipv4.tcp_keepalive_time', value: '600' }
    - { name: 'net.ipv4.tcp_keepalive_probes', value: '3' }
    - { name: 'net.ipv4.tcp_keepalive_intvl', value: '30' }
    - { name: 'vm.max_map_count', value: '262144' }
    - { name: 'vm.swappiness', value: '0' }
    - { name: 'vm.nr_hugepages', value: '0' }
    - { name: 'vm.overcommit_memory', value: '1' }
    - { name: 'vm.panic_on_oom', value: '0' }
    - { name: 'net.bridge.bridge-nf-call-iptables', value: '1' }
    - { name: 'net.bridge.bridge-nf-call-ip6tables', value: '1' }
    - { name: 'fs.inotify.max_user_instances', value: '8192' }
    - { name: 'vm.nr_hugepages', value: '1024' }

- name: 重新加载 sysctl 以应用新设置
  command: sysctl -p
  become: true

- name: Modify user limits
  lineinfile:
    dest: /etc/security/limits.conf
    line: "{{ item }}"
    create: yes  # 如果文件不存在，创建它
  with_items:
    - "* soft nproc 65535"
    - "* hard nproc 65535"
    - "* soft nofile 65535"
    - "* hard nofile 65535"

- name: Set temporary ulimit for the current shell session
  shell: "ulimit -SHn 65535"

- name: Create a systemd service to set ulimit at boot
  copy:
    content: |
      [Unit]
      Description=Set user limits at boot

      [Service]
      Type=oneshot
      ExecStart=/bin/sh -c "echo '* soft nproc 65535' >> /etc/security/limits.conf && echo '* hard nproc 65535' >> /etc/security/limits.conf && echo '* soft nofile 65535' >> /etc/security/limits.conf && echo '* hard nofile 65535' >> /etc/security/limits.conf"
      RemainAfterExit=yes

      [Install]
      WantedBy=multi-user.target
    dest: /etc/systemd/system/set-user-limits.service
    owner: root
    group: root
    mode: '0644'

- name: Reload systemd to apply new service
  systemd:
    daemon_reload: yes

- name: Enable and start the systemd service
  systemd:
    name: set-user-limits.service
    state: started
    enabled: yes

- name: Add permission to the systemd service file
  file:
    path: /etc/systemd/system/set-user-limits.service
    owner: root
    group: root
    mode: '0644'
